### ISSUE TITLE
Responsible stylesheet problem on start page

### ISSUE THREAD

**Issue by ponchofiesta** [tuub/platzbuchung#5]
There seems to be a CSS problem on the start page. When viewing with small screens (smartphones) the column count swtiches from 3 to 5. I assume it should be 3 to 1.

![platzbuchung-responsive](https://user-images.githubusercontent.com/12248938/94925515-9fba8d80-04bf-11eb-8347-8b8c6d456d8f.gif)

**Comment by johlton** [comment]
You're absolutely right, thanks Michael! :+1:
